### ISSUE TITLE
The patch command should always fail when a given patch is not applied

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#108]
### Examples

Assume `in.yaml`:
```
_plugin_configs: {}
data:
  hello: "world"
  stuffs: ["abc", "123"]
  foo: null
  bar:
  obj:
    dog: "barks"
```

A value that is `null`, an array, or a scalar cannot have an object patched. This should result in an error and a non-zero exit code. Currently the tool returns a  0 exit code and the unaffected input.
```
cat in.yaml | deck file patch --selector "$.data.foo" --value 'xyz:"abc"'
_plugin_configs: {}
data:
  bar: null
  foo: null
  hello: world
  obj:
    dog: barks
```

This ticket should also capture any additional ways that the patch command fails silently that we are aware of.

These are bugs and not breaking changes. Any existing users that "rely" on this broken behavior have the opportunity to resolve the incorrect usage of the tool because of the new raised failure.
