### ISSUE TITLE
Schema Regex patterns are not translated to regex paths

### ISSUE THREAD

**Issue by ashman1984** [Kong/go-apiops#109]
When using this library to convert an OAS spec to Kong declarative yaml, if a regex schema pattern is set in the OAS parameters for a path like so:

```
paths:
  /document-services/v1/generate/{template_id}:  
    parameters:
        - in: path
          name: template_id
          schema:
            type: string
            pattern: '[0-9a-zA-Z_-]+'
          required: true
          description: ID of the template to generate document from given content
```

The resulting conversion to Kong declarative yaml does not take into account this pattern when generating the path in route yaml:

```
    paths:
    - ~/document-services/v1/generate/(?<template_id>[^#?/]+)$
```

Unsure if this is a bug, a feature, not the intention of this library, or would have some other consequences that I am not aware of.

Please advise if this is something that would be considered a good addition to this library.
