### ISSUE TITLE
`oneOf` support in openapi2kong parameter schemas

### ISSUE THREAD

**Issue by mheap** [Kong/go-apiops#206]
The request validator plugin configuration generated by `openapi2kong` is invalid when using `oneOf`

```yaml
/test/data-type:
  get:
    parameters:
      - in: query
        name: mixed_number
        required: true
        schema:
          oneOf:
            - type: string
            - type: integer
```

Kong Gateway does not support mixed content types in a single parameter (FTI-2182), so `go-apiops` should return an error instead of generating an invalid configuration.

## Acceptance Criteria

- [ ] Parameter queries that use `oneOf` to specify multiple `type` fields in a single parameter result in an error being returned
