### ISSUE TITLE
Inconsistent results with recursive descent with filter expression

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#49]
In the repo we have a sample deck file: `docs/summertime-kong.yml` that has one service and one route and the route is defined under the service.

Applying a patch with a selector that uses recursive descent and a filter expression results in (I believe) inconsistent results:

The first example's selector is explicit in the path to the routes:
```
> kced patch -s docs/summertime-kong.yml --selector '$.services[*].routes[?(@.name=="summer-time_get")]' --value 'field:"foo"'
_format_version: "3.0"
services:
- host: mockbin.org
  id: b1525aee-d304-11ed-afa1-0242ac120002
  name: summer-time
  path: /requests
  plugins: []
  port: 443
  protocol: https
  routes:
  - field: foo
    id: b7d87736-d304-11ed-afa1-0242ac120002
    methods:
    - GET
    name: summer-time_get
    paths:
    - ~/summer-time$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags: []
```

In the second example we use recursive descent which should result in the same behavior, but do not get the expected results:
```
❯ kced patch -s docs/summertime-kong.yml --selector '$..routes[?(@.name=="summer-time_get")]' --value 'field:"foo"'
_format_version: "3.0"
services:
- host: mockbin.org
  id: b1525aee-d304-11ed-afa1-0242ac120002
  name: summer-time
  path: /requests
  plugins: []
  port: 443
  protocol: https
  routes:
  - id: b7d87736-d304-11ed-afa1-0242ac120002
    methods:
    - GET
    name: summer-time_get
    paths:
    - ~/summer-time$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags: []
```

Using https://jsonpath.com/ to validate, I see the following:

<img width="1128" alt="Screenshot 2023-04-21 at 9 52 28 AM" src="https://user-images.githubusercontent.com/10521262/233667451-adba4179-9a2e-46c5-8e99-8e0e675b1df2.png">

<img width="1121" alt="Screenshot 2023-04-21 at 9 52 37 AM" src="https://user-images.githubusercontent.com/10521262/233667467-a2f30fe0-c93c-454f-b9e8-7e4959dd95e5.png">
