### ISSUE TITLE
patch command will not add values to null key

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#80]
Take this input config (`input.yaml`)

```
# This will be used as the base file for
# all default _plugin_configs.  The actual
# defaults will be patched in incrementally
_plugin_configs:
```

And this patch file (`patch.yaml`):
```
_format_version: "1.0"
patches:
  - selectors:
    - $._plugin_configs
    values:
      default-jwt:
        name: jwt
        config:
          enabled: true
```

Ran as:
```
deck file patch -s input.yaml patch.yaml
```

Results in:
```
_plugin_configs: null
```

If I change `input.yaml` to:

```
# This will be used as the base file for
# all default _plugin_configs.  The actual
# defaults will be patched in incrementally
_plugin_configs:
  dummy:
```

The result will be:

```
_plugin_configs:
  default-jwt:
    config:
      enabled: true
    name: jwt
  dummy: null
```

The `patch` command should be able to create a new key in an existing null valued key.
